package com.skp.model;
// Generated 2017-1-18 16:30:04 by Hibernate Tools 5.2.0.CR1

/**
 * TAddress generated by hbm2java
 */
public class TAddress implements java.io.Serializable {

	private String addrId;
	private String userId;
	private String consignee;
	private String mobile;
	private String province;
	private String city;
	private String county;
	private String village;
	private String street;
	private String postalCode;
	private String isdefault;
	private Integer status;

	public TAddress() {
	}

	public TAddress(String addrId) {
		this.addrId = addrId;
	}

	public TAddress(String addrId, String userId, String consignee, String mobile, String province, String city,
			String county, String village, String street, String postalCode, String isdefault, Integer status) {
		this.addrId = addrId;
		this.userId = userId;
		this.consignee = consignee;
		this.mobile = mobile;
		this.province = province;
		this.city = city;
		this.county = county;
		this.village = village;
		this.street = street;
		this.postalCode = postalCode;
		this.isdefault = isdefault;
		this.status = status;
	}

	public String getAddrId() {
		return this.addrId;
	}

	public void setAddrId(String addrId) {
		this.addrId = addrId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getConsignee() {
		return this.consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(String isdefault) {
		this.isdefault = isdefault;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
